auth_access/urls.py
from django.urls import path
from . import views

app_name = 'auth'

urlpatterns = [
    path('', views.index, name='index'),
    path('token', views.get_token, name='get-token'),
    path('redirect', views.redirect_access, name='redirect'),
    path('logout', views.logout, name='logout')
]

frontend/urls.py
from django.urls import path
from . import views

app_name = 'frontend'

urlpatterns = [
    path('', views.index, name='index')
]

github_monitor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('auth_access.urls', namespace='auth')),
    path('api/', include('monitor.urls', namespace='monitor')),
    path('', include('frontend.urls', namespace='frontend'))
]

monitor/urls.py
from django.urls import path
from . import views

app_name = 'monitor'

urlpatterns = [
    path('repositories', views.RepositoryListCreateView.as_view(),
         name='repositories-list-create'),
    path('repositories/<str:repo_name>/commits',
         views.commits_by_repository, name='commits-by-repository'),
    path('push_event', views.push_event, name='push-event')
]

auth_access/models.py
from django.db import models

# Create your models here.

frontend/models.py
from django.db import models

# Create your models here.

monitor/models.py
from django.db import models
from django.utils import timezone


class Profile(models.Model):
    username = models.CharField(max_length=50, unique=True)
    name = models.CharField(max_length=100, null=True)
    email = models.EmailField()
    access_token = models.CharField(max_length=40, null=True)

    def __str__(self):
        return f'{self.name} <{self.username}>'


class Repository(models.Model):
    name = models.CharField(max_length=100, null=False)
    description = models.TextField(default='', null=True)
    owner = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        related_name='repositories'
    )
    full_name = models.CharField(
        max_length=201,
        unique=True,
        default='-')
    created_at = models.DateTimeField(default=timezone.now)
    hook_id = models.IntegerField(default=0, null=True)

    def __str__(self):
        return self.full_name

    def save(self, *args, **kwargs):
        self.full_name = f'{self.owner.username}/{self.name}'
        super(Repository, self).save(*args, **kwargs)

class Commit(models.Model):
    sha = models.CharField(max_length=40, unique=True)
    commiter = models.ForeignKey(
        Profile,
        null=True,
        on_delete=models.SET_NULL,
        related_name='commits'
    )
    commited_at = models.DateTimeField()
    message = models.TextField()
    repository = models.ForeignKey(
        Repository,
        on_delete=models.CASCADE,
        related_name='commits'
    )

    def __str__(self):
        return f'{self.message} {self.sha[:7]} <{self.repository.full_name}>'

auth_access/views.py
import requests
from decouple import config
from django.contrib import messages
from django.shortcuts import redirect, render
from github import Github

from monitor import helpers as monitor_helpers

from . import helpers as auth_helpers


@auth_helpers.logout_required
def index(request):
    return render(request, 'auth_access/index.html')


@auth_helpers.login_required
def logout(request):
    return auth_helpers.execute_logout(request)


@auth_helpers.logout_required
def get_token(request):
    # Todo: Create validations in case code and access_token return empty
    payload = {
        'code': request.GET.get('code'),
        'client_id': config('CLIENT_ID'),
        'client_secret': config('CLIENT_SECRET')
    }

    headers = {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
    }

    access = requests.post(
        'https://github.com/login/oauth/access_token',
        json=payload,
        headers=headers
    ).json()
    access_token = access.get('access_token')

    g = Github(access_token)
    user = g.get_user()

    profile = monitor_helpers.create_profile(
        username=user.login,
        name=user.name,
        email=user.email,
        access_token=access_token
    )

    auth_helpers.execute_login(request, profile.username)

    return redirect('frontend:index')


@auth_helpers.logout_required
def redirect_access(request):
    username = request.POST.get('username', None)

    if not username:
        messages.error(request, 'Enter your Github username',
                        extra_tags='danger')
        return redirect('auth:index')

    params = {
        'client_id': config('CLIENT_ID'),
        'login': username,
        'scope': ['write:repo', 'repo']
    }
    auth_url = auth_helpers.generate_url(
        'https://github.com/login/oauth/authorize', **params)

    return redirect(auth_url)

frontend/views.py
from django.shortcuts import render, redirect
from auth_access.helpers import login_required


@login_required
def index(request):
    return render(request, 'frontend/index.html')

monitor/views.py
from rest_framework import generics, status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from django.http.response import HttpResponse

from auth_access import helpers as auth_helpers

from . import helpers as monitor_helpers
from .tasks import insert_pushed_commits
from .models import Commit, Repository
from .serializers import CommitSerializer, RepositorySerializer


class RepositoryListCreateView(generics.ListCreateAPIView):
    queryset = Repository.objects.all()
    serializer_class = RepositorySerializer
    authentication_classes = (auth_helpers.GithubAuthentication, )

    def get_queryset(self):
        queryset = self.queryset
        if self.request.method == 'GET':
            username = self.request.session.get('username')
            queryset = monitor_helpers.get_repositories_by_user(username)

        return queryset

    def post(self, request, *args, **kwargs):
        username = request.session.get('username')
        serializer = RepositorySerializer(
            data=request.data,
            context={'username': username}
        )
        serializer.is_valid(raise_exception=True)
        serializer.save()
        headers = self.get_success_headers(serializer.data)
        return Response(
            serializer.data,
            status=status.HTTP_201_CREATED,
            headers=headers
        )


@api_view(['GET'])
@auth_helpers.login_required
def commits_by_repository(request, repo_name):
    username = request.session.get('username')
    repo_full_name = f'{username}/{repo_name}'
    commits = monitor_helpers.get_commits_by_repo(repo_full_name)

    paginator = monitor_helpers.MonitorPagination()
    return paginator.paginate_function_based_view(
                commits, request, CommitSerializer)


@api_view(['POST'])
def push_event(request):
    repository_info = request.data.pop('repository')
    commits_pushed = request.data.pop('commits')
    sender = request.data.pop('sender')

    insert_pushed_commits.delay(
        repository_info, commits_pushed, sender
    )

    return Response(status=status.HTTP_200_OK)

auth_access/templates/auth_access/index.html
{% extends 'frontend/base.html' %}
{% block content %}
    <main>
        <div class="jumbotron auth-login">
            <form action="{% url 'auth:redirect' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <h1>Github monitor</h1>
                    {% if messages %}
                        {% for message in messages %}
                        <div class="alert alert-dismissible alert-{{ message.tags }}">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            {{ message }}
                        </div>
                        {% endfor %}
                    {% endif %}
                    <label for="username">Github username</label>
                    <input type="text" class="form-control" id="username" name="username">
                  </div>
                <button class="btn btn-primary auth-button" type="submit">Enter</button>
            </form>
        </div>
    </main>
{% endblock %}

frontend/templates/frontend/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="{% static 'frontend/img/favicon.png' %}" type="image/png">
    <title>
        {% block title %} Github monitor {% endblock title %}
    </title>
    <link rel="stylesheet" href="https://bootswatch.com/4/darkly/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="{% static 'frontend/css/main.css' %}">
</head>
<body>
    {% block content %}
    {% endblock content %}
    <!-- bootstrap -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

frontend/templates/frontend/index.html
{% extends 'frontend/base.html' %}
{% load static %}
{% block content %}
    <div id='app'></div>
    <script src="{% static 'frontend/js/main.js' %}"></script>
{% endblock content %}